config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :shops do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      get :favorite
      get :tweetfavorite
      get :sale
      get :buy
    end
    member do
      get :follow
      get :followees
      get :follower
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :tweets do
    resources :tweet_comments
    collection do
      get 'search'
    end
    member do
      get :favorite
    end
  end
  resources :notifications, only: [:index]
  resources :rooms, only:[:index,:create,:show]
  resources :messages, only:[:create]

  resources :items do
    member do
      get :favorite
    end
    collection do
      get 'search'
      get 'category'
    end
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :tweet_comments, dependent: :destroy
  acts_as_likeable
  has_many :notifications, dependent: :destroy


  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and tweet_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        tweet_id: id,
        visited_id: user_id,
        action: 'like'
      )
      unless notification.visitor_id == notification.visited_id
        notification.save if notification.valid?
      end
    end
  end



  def create_notification_comment!(current_user, tweet_comment_id)
    temp_ids = TweetComment.select(:user_id).where(tweet_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, tweet_comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, tweet_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, tweet_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      tweet_id: id,
      tweet_comment_id: tweet_comment_id,
      visited_id: visited_id,
      action: 'tweetcomment'
    )
    unless notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end


  

  def was_attached?
    self.image.attached?
  end

  def self.search(search)
    if search != ""
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end

  with_options presence: true do
    validates :text
    validates :image
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :create, :edit, :update, :destroy, :search]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy, :favorite]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to search_tweets_path
    else
      render :new
    end
  end

  def show
      @comment = TweetComment.new
      @comments = @tweet.tweet_comments.includes(:user)
  end

  def update
    if @tweet.update(tweet_params)
        redirect_to tweet_path
    else
        render :edit
    end
  end

  def destroy
    if @tweet.destroy
      redirect_to search_tweets_path
    end
  end

  def search
    @q = Tweet.ransack(params[:q])
    @tweets = @q.result.includes(:user).order("created_at DESC")
  end
      
  def favorite
    current_user.toggle_like!(@tweet)
    redirect_to request.referer
    @tweet.create_notification_like!(current_user)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    unless Tweet.find(params[:id]).user.id == current_user.id
      redirect_to root_path
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<%= render partial: "shared/tweet", locals:{ tweet: @tweet}%>
 <%= render partial: "shared/second-footer" %> 

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= render partial: "shared/tweet", locals:{ tweet: @tweet}%>
  </div>
</div>
<%= render partial: "shared/second-footer" %>

app/views/tweets/search.html.erb
<%= render partial: 'shared/header'%>
<%= render partial: 'shared/tweet_search' %>
 <%= render partial: "shared/second-footer" %> 

app/views/tweets/show.html.erb
<%= render "shared/header" %>

<div class="main">
<div class="tweet_show_main">
 <div class="tweet_show">
   <div class="tweet_left">
    <div class="tweet_show_list">
      <div class="show_image_text">
        <%= image_tag @tweet.image, class:'tweet_show_image',id: 'message-image' if @tweet.image.attached?%>
         <% if user_signed_in? %>
           <div class="show_like_comment">
              <%= link_to favorite_tweet_path(@tweet) do %>
              <% if current_user.likes?(@tweet)%>
              <div class="tweet_like">
               <%= image_tag("redlike",class:"tweet_btn")%>
               <%=@tweet.likers_count%>
              </div>
               <%else%>
                <div class="tweet_like">
                 <%= image_tag("like",class:"tweet_btn")%>
                 <%=@tweet.likers_count%>
                </div>
              <%end%>
             <%end%>
            <%end%>
          </div>
        <div class="tweet_show_text">
         <%= @tweet.text%>
        </div>
         <div class="tweet_show_time">
          <%= @tweet.updated_at.strftime('%Y/%m/%d %H:%M') %>
         </div>
       </div>
      </div>
     </div>

    <%# comment ---------%>
   <div class="comment_right">
    <div class="tweet_sticky">
      <div class="tweet_show_user_information">
       <%= link_to user_path(@tweet.user.id) do%>
         <% if @tweet.user.image.present? %>
         <%= image_tag @tweet.user.image, class:'tweet_show_default',id: 'message-image'%>
         <%= link_to @tweet.user.nickname, user_path(@tweet.user.id), class: :tweet_show_user %>
         <%else%>
         <%= link_to image_tag("human", class:"tweet_show_default"),user_path(current_user.id) %>
         <div class="tweet_show_user">
         <%= @tweet.user.nickname%>
         </div>
         <%end%>
         <%end%>
          <div class="one_more">
           <ul class="one_more_list">
            <% if @tweet.user_id == current_user.id%>
             <li>
              <%= link_to image_tag("edit", class: :one_edit), edit_tweet_path(@tweet.id), method: :get %>
            </li>
            <li>
             <%= link_to image_tag("destroy",class: :one_delete ), tweet_path(@tweet.id), method: :delete,data: {confirm: "削除しますか？"}%>
            </li>
           </ul>
           <%end%>
          </div>
       </div>

    <div class="tatata">
      <% @comments.each do |comment| %>
       <div class="comments">
        <div class="comment-content">
         <div class="tweet_comment_nickname_image">
         <% if comment.user.image.present? %>
          <%= image_tag comment.user.image, class:'tweet_default',id: 'message-image'%>
          <%else%>
         <%= link_to image_tag("human", class:"tweet_default"),user_path(current_user.id) %>
         <%end%>
           <div class="comment-name">
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %></strong>
           </div>
         </div>
         <div class="comment_text_time">
       <div class="comment_text">
        <%= comment.text %>
       </div>
        <div class="show_tweet_time">
          <%= " #{time_ago_in_words(comment.created_at)}前" %>
         </div>
         </div>

     </div>

    </div>
    <% end %>
   </div>

    <div class="comment-box">
      <% if user_signed_in? %>
      <%= form_with(model: [@tweet, @comment], local:true) do |t|%>
      <%= t.text_area :text, class: "comment-form", placeholder: "コメントする", rows: "2" %>
       <p class="comment-warn">相手のことを考えたコメントを心がけましょう。</p>
      <%= t.submit "コメント", class: :comment_btn %>
    </div>
    
      <% end %>
      <% else %>
       <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>
     </div>
    </div>
   </div>
</div>
</div>

  <%# /コメント %>

<%= render partial: "shared/second-footer" %> 