config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :shops do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      get :favorite
      get :tweetfavorite
      get :sale
      get :buy
    end
    member do
      get :follow
      get :followees
      get :follower
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :tweets do
    resources :tweet_comments
    collection do
      get 'search'
    end
    member do
      get :favorite
    end
  end
  resources :notifications, only: [:index]
  resources :rooms, only:[:index,:create,:show]
  resources :messages, only:[:create]

  resources :items do
    member do
      get :favorite
    end
    collection do
      get 'search'
      get 'category'
    end
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :orders
  has_many :comments
  has_many :tweets, dependent: :destroy
  has_many :tweet_comments
  has_one_attached :image
  acts_as_liker
  acts_as_follower
  acts_as_followable
  has_one :shop, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :room_users
  has_many :room_users, dependent: :destroy

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy


  validates :nickname, presence: true, unless: :was_attached?


  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end


  def was_attached?
    self.image.attached?
  end

  with_options presence: true do
    validates :nickname
    with_options format: { with: /\A([ぁ-んァ-ン一-龥々]|ー)+\z/} do
      validates :first_name
      validates :last_name
    end

    with_options format: { with: /\A([ァ-ン]|ー)+\z/} do
      validates :first_kana
      validates :last_kana
    end
    
     validates :birthday
  end

  validates :password, length: { minimum: 6 }, on: :create
  # validates :password_confirmation, presence: true, on: :create

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください',on: :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :follow, :followees, :follower]
  before_action :move_to_index, only: [:edit, :update]
  
  def show
    @items = @user.items
    @tweets = @user.tweets.order("created_at DESC")
    @shop = @user.shop

    @currentUserEntry = RoomUser.where(user_id: current_user.id)
    @roomUser = RoomUser.where(user_id: @user.id).select("room_id")

    @star = RoomUser.where(room_id: current_user.id)

    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @roomUser.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      if @isRoom
      else
        @room = Room.new
        @entry = RoomUser.new
      end
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def favorite
    @user = current_user
    @favorites = @user.likees(Item)
  end

  def tweetfavorite
    @user = current_user
    @favorites = @user.likees(Tweet)
  end

  def follow
    current_user.toggle_follow!(@user)
    redirect_to user_url @user

    @user.create_notification_follow!(current_user)
  end

  def followees
    @favorites = @user.followees(User)
  end

  def follower
    @favorites = @user.followers(User)
  end

  def buy
    @item = Order.where(user_id: current_user.id).select("item_id")
  end

  def sale
    @item = Item.joins(:order).where(items: {user_id: current_user.id})
  end
  
  private
  def user_params
    params.require(:user).permit(:nickname, :first_name, :last_name, :first_kana, :last_kana, :email, :birthday, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def move_to_index
    unless User.find(params[:id]).id == current_user.id
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/buy.html.erb
<%= render "shared/header" %>

<div class="main">
<div class="account">
 <div class="account_title">購入したITEM
 </div>
  <%if @item.present?%>
 <div class="account_list">
  <% @item.each do |i|%>
   <div class="account_infomation">
     <%= link_to item_path(i.item) do %>
     <div class="account_content">
      <div class="account_image_content">
        <%= image_tag (i.item.image),class:"account_image"%>
      </div>
      <div class="account_item">
       <div class="account_name">
        <%= i.item.name%>
       </div>

       <div class="account_price">
        ¥<%= i.item.price%>
       </div>

        <div class="account_time">
         <%= i.item.updated_at.strftime('%Y/%m/%d')%>
        </div>
      </div>
     </div>
   </div>
      <%end%>
    <%end%>
    <%else%>
    <div class="not_item_favorite">
     <%= link_to image_tag("shopping",class:"not_favorite_image"),search_items_path %>
      <p>購入済みの商品がありません...</p>
    </div>
    <%end%>
 </div>
</div>
</div>
<%= render partial: "shared/second-footer" %> 

app/views/users/edit.html.erb
<%= render partial: "shared/second-header"%>

<%= form_with model: @user ,class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報入力
    </h1>
  </div>

  <%#= render 'shared/error_messages', model: f.object %>
  <div class="user_image_list">
   <div id="image-list"></div>
  </div>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="form-group">
    <div class='form-text-wrap'>
     <%= f.file_field :image, class: 'user_image_preview', id:"message_image" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) furima太郎", maxlength:"18" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
 
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_kana, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>

  <div class="form-group">
    <h2 class='form-bottom-text'>
      「会員登録」のボタンを押すことにより、
      <span>利用規約</span>
      <br>に同意したものとみなします
    </h2>
  </div>
  <div class='register-btn'>
    <%= f.submit "変更する" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>

<%= render partial: "shared/second-footer"%>

app/views/users/favorite.html.erb
<%= render "shared/header" %>

<div class="main">
<div class="item_favorite">
 <div class="favorite">

  <div class="favorite_title">
    <h1>お気に入り</h1>
  </div>
  
  <%if @favorites.present?%>
    <div class="favorite_style">
      <% @favorites.each do |favorite| %>

      <div class="favoreite_list">
        <div class="favorite_content">
          <%= link_to item_path(favorite) do %>
           <div class="favorite_image_list">
            <%= image_tag favorite.image, class: "favorite_image" %>
             <% if favorite.order != nil%>
              <div class="sold-out">
               <%= image_tag("sold_out")%>
              </div>
          <% end %>
           </div>
      <div class="ale">
        <div class="konnnitiha">
          <div class="favorite_text">
            <h5 class="favorite_name"><%= favorite.name %></h5>
              <div onclick="favorite('<%= item_path(favorite) %>/favorite')">
               <%= image_tag("destroy",class:"item_favorite_delete")%>
              </div>
          </div>
           <div class="dosss">
            <div class="favorite_price">￥<%= favorite.price %></div>
           </div>
        </div>
         <div class=item_favorite_right>
            <div class="cos">
                <%= image_tag "right_yazirusi",class:"yazirusi"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <%else%>

    <div class="not_item_favorite">
     <%= link_to image_tag("shopping",class:"not_favorite_image"),search_items_path %>
      <p>お気に入りに商品がありません...</p>
    </div>
    <%end%>

  </div>
 </div>
</div>
</div>

<script>
function favorite(url) {
    var req = new XMLHttpRequest();
    req.onreadystatechange = function() {
      if (req.readyState == 4) {
        location.reload();
      }
    }
    req.open('GET', url, true);
    req.send(null);
}
</script>

<%= render "shared/second-footer"%>

app/views/users/followees.html.erb
<%= render "shared/header" %>

<div class="follow">
  <div class="follow_title">
   <h1>フォローリスト</h1>
  </div>

  <%if @favorites.present?%>
   <div class="follow_style">
    <% @favorites.each do |favorite| %>
    <div class="follow_list">
      <%= link_to user_path(favorite) do%>

     <div class="follow_content">
     <% if favorite.image.present? %>
      <%= image_tag(favorite.image,class:"follow_image")%>
       <%else%>
        <%= link_to image_tag("human", class:"follow_image"),user_path(current_user.id) %>
        <%end%>
       <div class="alea">
        <div class="follow_text">
         <div class= "follow_nickname">
          <h5><%= favorite.nickname%></h5>
         </div>
         <% if favorite.shop.present?%>
          <div class="follow_shop_text">
           <%= favorite.shop.text.truncate(100)%>
          </div>
          <%end%>
         <%end%>
        </div>
     </div>
    </div>
    <%end%>
    <%else%>
    <div class="not_item_favorite">
      <%= link_to image_tag("follow",class:"not_favorite_image"),search_items_path %>
       <p>フォローメンバーがいません...</p>
    </div>
    <%end%>
</div>

app/views/users/follower.html.erb
<%= render "shared/header" %>

<div class="follow">
  <div class="follow_title">
   <h1>フォロワーリスト</h1>
  </div>

  <%if @favorites.present?%>
   <div class="follow_style">
    <% @favorites.each do |favorite| %>
     <div class="follow_list">
      <%= link_to user_path(favorite) do%>

      <div class="follow_content">
      <% if favorite.image.present? %>
       <%= image_tag(favorite.image,class:"follow_image")%>
        <%else%>
         <%= link_to image_tag("human", class:"follow_image"),user_path(current_user.id) %>
         <%end%>
        <div class="alea">
          <div class="follow_text">
            <div class= "follow_nickname">
              <h5><%= favorite.nickname%></h5>
            </div>
            <% if favorite.shop.present?%>
              <div class="follow_shop_text">
                <%= favorite.shop.text.truncate(100)%>
              </div>
              <%end%>
             <%end%>
          </div>
        </div>
       </div>
        <%end%>
        <%else%>
        <div class="not_item_favorite">
         <%= link_to image_tag("follow",class:"not_favorite_image"),search_items_path %>
          <p>フォロワーがいません...</p>
        </div>
        <%end%>
</div>

app/views/users/sale.html.erb
 <%= render "shared/header" %>

<div class="main">
<div class="account">
  <div class="account_title">売上履歴</div>
     <%if @item.present?%>
       <div class="account_list">
         <% @item.each do |i|%>
    
           <div class="account_infomation">
            <%= link_to item_path(i) do%>
    
             <div class="account_content">
               <div class="account_image_content">
                 <%= image_tag (i.image),class:"account_image"%>
               </div>

               <div class="account_item">
                 <div class="account_name">
                   <%= i.name%>
                 </div>

                 <div class="account_price">
                   ¥<%= (i.price * 0.9).floor%>
                 </div>

                   <div class="account_time">
                    <%= i.updated_at.strftime('%Y/%m/%d')%>
                   </div>
               </div>
             </div>
        </div>
        <%end%>
        <%end%>
        <%else%>
        <div class="not_item_favorite">
         <%= image_tag "money",class:"not_favorite_image" %>
           <p>売却済みの商品がありません...</p>
        </div>
        <%end%>
  </div>
</div>
</div>
<%= render partial: "shared/second-footer" %> 

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <%= render partial:"shared/user_side_bar"%>

        <div class="page-heading">
         <div class="user_left">
           <% if @user.image.present? %>

             <div class="user_top_img">
              <%= image_tag(@user.image, class: 'user-image', id: 'message_image')%>
             </div>
           <%else%>
             <div class="user_top_img">
               <%= link_to image_tag("human", class:"user-image")%>
             </div>
           <%end%>
         </div>
         <div class="user_right">

          <div class="user_profile">
           <div class="user_profile_nickname">
             <div class= "user_nickname">
               <%= @user.nickname %>
             </div>
             <%if @user.id == current_user.id%>
             <div class="two_edit">
               <%= link_to image_tag("profile",class:"user_edit"),edit_user_path(@user)%>
               <% if @shop.present?%>
               <%= link_to image_tag("shop",class:"user_edit"),edit_shop_path(@shop)%>
             </div>
               <%end%>
               <%end%>
               <% unless @user.id == current_user.id %>
                <% if @isRoom == true %>
                <div class="user_chat">
                  <a href="/rooms/<%= @roomId %>" class="chat2">MESSAGE</a>
                </div>
                <%else%>
                 <%= form_for @room do |f| %>
                 <%= fields_for @entry do |e| %>
                 <%= e.hidden_field :user_id, value: @user.id %>
                <% end %>
                  <div class="user_chat">
                    <%= f.submit "MESSAGE", class:"chat"%>
                 </div>
                <%end%>
                <%end%>
                <%end%>
                <%if @shop.present?%>
                 <div class="show_shop_image">
                  <%= image_tag(@user.shop.image,clsss:"shop_images")%>
                 </div>
                 <%end%>
                </div>
               </div>

                 <div classs="follow_ask">
                   <% unless @user.id == current_user.id%>
                    <%= link_to follow_user_path do %>
                      <% if current_user.follows?(@user)%>
                        <div class="follow_cancel">フォロー中</div>
                    <%else%>
                        <div class="follow_action">フォロー</div>
                    <%end%>
                   <%end%>
                 <%end%>
                 
              
           
          

           <div class="follow_number">
            <div class="follow_contents_number">
             <%= link_to follower_user_path(@user) do%>
              <div class="follow_number_count">
                  <div class="follow_number_text">フォロワー</div>
                  <%= @user.followers_count%>人
              </div>
             <%end%>
            </div>

            <div class="follow_contents_number">
              <%= link_to followees_user_path(@user) do%>
               <div class="follow_number_count">
                 <div class="follow_number_text">フォロー中</div>
                 <%= @user.followees_count%>人
               </div>
              <%end%>
            </div>
       </div>

       <%if @shop.present?%>
           <table class="user-table">
            <tbody>
              <tr>
              <th class="detail-shop">SHOP名</th>
              <td class="detail-user"><%= @shop.name %></td>
             </tr>
             <tr>
              <th class="detail-shop">CATEGORY</th>
              <td class="detail-user"><%= @shop.shop_category.name %></td>
             </tr>
             <tr>
              <th class="detail-shop">都道府県</th>
              <td class="detail-user"><%= @shop.prefecture.name %></td>
             </tr>
            </tbody>
           </table>

            <div class="grad-wrap">
             <input id="trigger1" class="grad-trigger" type="checkbox">
              <div class="grad-item"><%= @shop.text%></div>
               <label class="grad-btn" for="trigger1"></label>
              </div>
              <%else%>
             </div>
            </div>

              <div class="show_shop_image">
                <%= image_tag("sky",class:"shop_images")%>
              </div>
              <div class="shop_make">
                <%= link_to "SHOPを作る" , new_shop_path %>
              </div>
              <%end %>
          </div>
        </div>
      </div>
    </div>

      <div class="item_tweet_main">
  <h1 class="item_title">STORY</h1>
   <%= render partial: "shared/tweet_scroll"%>
   </div>
   <div class="item_title">ITEM</div>
   <%= render partial: 'items/item' %>
</div>
<%= render partial: "shared/second-footer" %> 

app/views/users/tweetfavorite.html.erb
<%= render "shared/header" %>

<div class="main">
<div class="twitter">
 <div class="tweet_side">

   <div class="side_text">
    <div class="tweet_favorite_title">お気に入り</div>
      <%= link_to root_path do%>
       <div class="tweet_side_image">
         <%= image_tag("home",class:"tweet_home")%>
           <div class="side_tag">HOME</div>
       </div>
       <%end%>

       <%= link_to search_tweets_path do%>
       <div class="tweet_side_image">
        <%= image_tag("star",class:"tweet_home")%>
         <div class="side_tag">STORY一覧</div>
       </div>
       <%end%>

     <%= link_to new_tweet_path do%>
      <div class="tweet_side_image">
       <%= image_tag("tweets",class:"tweet_home")%>
        <div class="side_tag">投稿</div>
      </div>
      <%end%>
     </div>
  </div>

  <%if @favorites.present?%>
   <div class="tweet_main">
     <% @favorites.each do |favorite| %>
      <div class="tweet_list">
        <div class="tweet_user_information">
          <% if favorite.user.image.present? %>
           <%= link_to image_tag(favorite.user.image, class:'tweet_default')%>
          <%else%>
            <%= link_to image_tag("human", class:"tweet_default"),user_path(current_user.id) %>
          <%end%>
            <%= link_to favorite.user.nickname, user_path(favorite.user.id), class: :tweet_user %>
             <div class="tweet_time">
              <%= favorite.updated_at.strftime('%Y/%m/%d %H:%M') %>
             </div>
        </div>
        <%= link_to(tweet_path(id: favorite.id)) do%>
         <div class="image_text">
          <%= image_tag favorite.image, class:'tweet_image',id: 'message-image' if favorite.image.attached?%>
            
           <div class="like_comment">
             <%= link_to favorite_tweet_path(favorite) do %>
              <% if current_user.likes?(favorite)%>
               <div class="tweet_like">
               <%= image_tag("redlike",class:"tweet_btn")%>
               <%=favorite.likers_count%>
              </div>
             <%else%>
             <div class="tweet_like">
              <%= image_tag("like",class:"tweet_btn")%>
              <%=favorite.likers_count%>
             </div>
             <%end%>
            <%end%>
            <div class="tweet_like">
             <%= link_to image_tag("comment", class:"tweet_btn"),tweet_path(id: favorite.id)%>
            </div>
          </div>
           <div class="tweet-wrap">
            <label class="tweet-btn" ></label>
          <div class="tweet-item"><%= favorite.text%></div>
        </div>
      </div>
    </div>
   <%end%>
   <%end%>
  </div>
  <%else%>
  <div class="favorite_tweet_main">
  <div class="not_tweet_favorite">
    <%= link_to image_tag("tweets",class:"not_favorite_image"),search_tweets_path %>
     <p>お気に入りにSTORYがありません...</p>
  </div>
   <%end%>
   </div>
</div>
</div>



<%= render "shared/second-footer"%>