config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :shops do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      get :favorite
      get :tweetfavorite
      get :sale
      get :buy
    end
    member do
      get :follow
      get :followees
      get :follower
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :tweets do
    resources :tweet_comments
    collection do
      get 'search'
    end
    member do
      get :favorite
    end
  end
  resources :notifications, only: [:index]
  resources :rooms, only:[:index,:create,:show]
  resources :messages, only:[:create]

  resources :items do
    member do
      get :favorite
    end
    collection do
      get 'search'
      get 'category'
    end
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
 <div class="error-alert">
   <ul>
     <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='top-header'>
   <div class='search-bar-contents'>
    <%= link_to image_tag("give_icon", class:"give-icon"), root_path %>
   </div>

    <div class='nav'>
     <ul class='lists-right'>
      <% if user_signed_in? %>
    
       <li>
        <%= link_to notifications_path do%>
         <%= image_tag("bell",class:"bell_btn")%>
         <% if unchecked_notifications.any? %>
          <%= image_tag("maru",class:"circle")%>
         <% end %>
        <%end%>
       </li> 
     
       <li><%= link_to image_tag("home",class:"header_image"),root_path%></li>
       <li><%= link_to image_tag("camera",class:"header_image"),new_item_path%></li>
       <li><%= link_to image_tag("tweets",class:"header_image"),new_tweet_path%></li>
       <% if current_user.image.present? %>
         <li><%= link_to image_tag(current_user.image,class: "header_user_icon"),user_path(current_user.id) %></li>
       <%else%>
         <%= link_to image_tag("human", class:"header_user_icon"),user_path(current_user.id) %>
       <%end%>
       <%else%>
        <li><%= link_to 'ログイン', new_user_session_path, class: "header-content" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "header-content" %></li>
     </ul>
      <% end %>
    </div>
   </div>

  <div class="header_search">
    <div class="header_right">
     <%= link_to "ITEMを探す",search_items_path,class:"header_search_list"%>
     <%= link_to "SHOPを探す",search_shops_path,class:"header_search_list"%>
     <%= link_to "STORYを探す",search_tweets_path,class:"header_search_list"%>
    </div>
    <div class="header_left">
      <%= link_to "STORYを投稿する",new_tweet_path,class:"header_search_list"%>
      <%= link_to "出品する",new_item_path,class:"header_search_list"%>
    </div>
  </div>
</header>

app/views/shared/_item_box.html.erb
<div class="items-sell-contents">
 <%= render "shared/second-header"%>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with(model: @item, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
      <div id="image-list"></div>
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, class: 'olddd', id:'message_image' %>
      </div>
    </div>
    <%# /出品画像 %>

    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 18文字まで)", maxlength:"18" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_charge_id, DeliveryCharge.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
         <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
     <p>販売手数料は10%です。売り上げ利益から自動で引かれます。</p>
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

<script>
function tax() {
  const itemPrice = document.getElementById("item-price");
    itemPrice.addEventListener('change', () => {
      const price = itemPrice.value;
      const addTaxPrice = document.getElementById("add-tax-price");
      const profit = document.getElementById("profit");
      const taxPrice = Math.floor(price * 0.1);
      const saleProfit = price - taxPrice;

      addTaxPrice.innerHTML = taxPrice;
      profit.innerHTML = saleProfit;
  });
}
window.addEventListener("load" , tax);
</script>

app/views/shared/_item_search.html.erb
<div class="wrapper">
  <div class="side-bar">

    <div class="search_category">
     <div class="search_items">

       <%= search_form_for @p, url: search_items_path do |f| %>
        <div class="search_item">
         <%= f.label :name_cont, '商品名',class: :item_search_content %>
         <br>
         <%= f.text_field :name_cont, placeholder: '商品名',class: :item_form %>
        </div>

       <div class="search_item">
        <%= f.label :category_id_eq, 'カテゴリー',class: :item_search_content %>
        <br>
        <%= f.collection_select(:category_id_eq, @item_category, :id, :name, {include_blank: '指定なし'},class: :item_form)%>
       </div>

     <div class="search_item">
      <%= f.label :delivery_charge_id_eq, '配送料',class: :item_search_content %>
      <br>
      <%= f.collection_select(:delivery_charge_id_eq, @item_delivery_charge, :id,:name, {include_blank: '指定なし'},class: :item_form)%>
     </div>

     <div class="search_item">
       <%= f.label :day_id_eq, '発送日',class: :item_search_content %>
       <br>
       <%= f.collection_select(:day_id_eq, @item_day, :id, :name, {include_blank: '指定なし'},class: :item_form)%>
     </div>

     <div class="search_item">
       <%= f.label :price_gteq, '価格',class: :item_search_content%>
       <br>
       <%= f.number_field :price_gteq ,class: :search_form%>〜
       <%= f.number_field :price_lteq, class: :search_form %>
     </div>

     <div class="item_submit">
      <%= f.submit '検索',class:"search_submit" %>
     </div>
   </div>
  </div>
  <% end %>
 </div>

  <% if @results.length !=0 %>
    <div class='item-contents'>
      <ul class='item-lists'>
       <% @results.each do |item| %>

        <li class='list'>
         <%= link_to item_path(id: item.id) do %>
           <div class='item-img-content'>
            <%= image_tag(item.image, class: "item-img") %>
              <% if item.order != nil %>
               <div class='sold-out'>
                <%= image_tag("sold_out")%>
               </div>
              <% end%>
           </div>
       
          <div class='item-info'>
            <h3 class='item-name'>
              <%= item.name %>
            </h3>
             <div class='item-price'>
              <span><%= item.price %>円<br><%= item.delivery_charge.name %></span>
             </div>
           </div>
        </li>
        
       <%end%>
       <%end%>
     </ul>
      <%else%>
      <div class="not_search_item">
       <h1>該当する商品はありません</h1>
      </div>
      
     <% end %>
    </div>
</div>
 <%= paginate @results%>
 <%= render partial: "shared/second-footer" %> 

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <%= image_tag "give_icon.png", class:"second-fotter-logo"%>
    <div class='second-fotter-text-wrap'>
      <p class='second-fotter-text'>プライバシーポリシー</p>
      <p class='second-fotter-text'>FURIMA利用規約</p>
      <p class='second-fotter-text'>特定商取引に関する表記</p>
    </div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("give_icon.png", class:"second-logo"), "/" %>
</header>

app/views/shared/_shop.html.erb
<%= render "shared/header" %>
<div class= "shop_create">
  <%= form_with(model: @shop, local: true) do |f| %>
  <h2 class="items-sell-title">SHOP情報を入力</h2>
  <%= render 'shared/error_messages', model: f.object %>
   <div class="form-group">
     <div class='form-text-wrap'>
      <label class="form-text">SHOPイメージ</label>
       <span class="indispensable">必須</span>
        <div class="shop_image_list">
         <div id="image-list"></div>
        </div>
          <%= f.file_field :image, id:"message_image" %>
       </div>
     </div>

     <div class="form-group">
       <div class='form-text-wrap'>
        <label class="form-text">SHOP名</label>
        <span class="indispensable">必須</span>
       </div>
       <%= f.text_area :name, id:"shop-name", placeholder:"SHOP名（必須 18文字まで)", maxlength:"18" %>
     </div>

      <div class="form-group">
       <div class='form-text-wrap'>
        <label class="form-text">SHOPストーリー</label>
         <span class="indispensable">必須</span>
       </div>
        <%= f.text_area :text, id:"shop-text", placeholder:"SHOPストーリー (必須 1000文字まで)" ,rows:"7" ,maxlength:"1000" %>
      </div>

      <div class="form-group">
       <div class='form-text-wrap'>
        <label class="form-text">出品カテゴリー</label>
         <span class="indispensable">必須</span>
       </div>
        <%= f.collection_select(:shop_category_id, ShopCategory.all, :id, :name, {}, {class:"shop_select_box", id:"shop_category"}) %>
      </div>

      <div class="form-group">
       <div class='form-text-wrap'>
        <label class="form-text">都道府県</label>
         <span class="indispensable">必須</span>
       </div>
         <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"shop_select_box", id:"item-prefecture"}) %>
       </div>


    <div class='shops-btn'>
      <%= f.submit "SHOP" ,class:"shop-btn" %>
    </div>
    <%end%>
   </div>

<%= render partial: "shared/second-footer"%>

app/views/shared/_tweet.html.erb
<%= render partial: 'shared/header'%>

<div class="new_tweet">
 <div class="new_tweet-image">
  <div class= "tweet_preview">
   <div id="image-list"></div>
  </div>
 </div>

  <%= form_with(model: @tweet, local: true) do |form| %>
  <%= render 'shared/error_messages', model: form.object %>
   <div class="tweet_new-text">
    <div class="tweet_all">
      <%= form.file_field :image, class:"tweet_images" ,id:'message_image'%>
      <%= form.text_area :text, class:"tweet_text", placeholder:"STORY（必須 150文字まで)", maxlength:"150"%>
      <%= form.submit "投稿",class:"tweet_submit" %>
    </div>
   </div>
  <%end%>
</div> 

app/views/shared/_tweet_scroll.html.erb
   <ul class="horizontal-list">
    <% if @tweets.present? %>
     <% @tweets.each do |tweet| %>
      <li class="item">

       <div class="item_tweet_list">
        <div class="item_image_text">
         <%= link_to image_tag(tweet.image, class:'item_tweet_image',id: 'message-image'),tweet_path(id: tweet.id) if tweet.image.attached?%>
        </div>
         <div class="item_tweet_user_informations">
          <% if tweet.user.image.present? %>
           <%= link_to image_tag(tweet.user.image, class:'item_tweet_user_image',id: 'message-image')%>
          <%else%>
           <%= link_to image_tag("human", class:"item_tweet_user_image"),user_path(tweet.user.id) %>
          <%end%>
           <%= link_to tweet.user.nickname, user_path(tweet.user.id), class: :item_tweet_user %>
         </div>
          <div class="index_tweet_text">
           <%= tweet.text%>
         </div>

          <div class="index_tweet_time">
            <%= link_to "詳しく見る",tweet_path(id: tweet.id)%>
          </div>
        <%end%>
       </div>

      </li>
   </ul>
     <%else%>
      <h3 class='item-non'>STORYが投稿されていません。</h3>
     <% end%>
     </div>

app/views/shared/_tweet_search.html.erb
<div class="main">
<div class="twitter">
  <%#side_bar%>
 <div class="tweet_side">
   <div class="side_text">
     <div class="tweet-search">
      <div class="tweet-search-content">
        <%= search_form_for @q, url: search_tweets_path do |f| %>
         <div class="search_form">
          <div class="search_forms">
            <%= f.text_field :text_cont,class:"input-box" %>
            <%= f.submit '検索',class:"search-button" %>
          </div>
         </div>
         <%end%>
      </div>
     </div>

      <%= link_to root_path do%>
       <div class="tweet_side_image">
        <%= image_tag("home",class:"tweet_home")%>
         <div class="side_tag">HOME</div>
       </div>
      <%end%>

      <%= link_to tweetfavorite_users_path do%>
       <div class="tweet_side_image">
        <%= image_tag("star",class:"tweet_home")%>
         <div class="side_tag">お気に入り</div>
       </div>
      <%end%>

     <%= link_to search_tweets_path do%>
      <div class="tweet_side_image">
       <%= image_tag("top",class:"tweet_home")%>
        <div class="side_tag">TOPへ戻る</div>
      </div>
     <%end%>

     <%= link_to new_tweet_path do%>
      <div class="tweet_side_image">
       <%= image_tag("tweets",class:"tweet_home")%>
        <div class="side_tag">投稿</div>
      </div>
     <%end%>
   </div>
 </div>
 <%#side_bar%>

 <%#STORY一覧%>
  <%if @tweets.present?%>
   <div class="tweet_main">
     <% @tweets.each do |tweet| %>
      <div class="tweet_list">
       <div class="tweet_user_information">
        <% if tweet.user.image.present? %>
         <%= link_to image_tag(tweet.user.image, class:'tweet_default')%>
        <%else%>
         <%= link_to image_tag("human", class:"tweet_default"),user_path(tweet.user.id) %>
        <%end%>
         <%= link_to tweet.user.nickname, user_path(tweet.user.id), class: :tweet_user %>
          <div class="tweet_time">
            <%= tweet.updated_at.strftime('%Y/%m/%d %H:%M') %>
          </div>
       </div>

        <%= link_to (tweet_path(id: tweet.id)) do%>
        <div class="image_text">
         <%= image_tag tweet.image, class:'tweet_image',id: 'message-image' if tweet.image.attached?%>
         
          <%#like%>
        <div class="like_comment">
           <%= link_to favorite_tweet_path(tweet) do %>
           <% if current_user.likes?(tweet)%>
            <div class="tweet_like">
              <%= image_tag("redlike",class:"tweet_btn")%>
              <%=tweet.likers_count%>
            </div>
             <%else%>
              <div class="tweet_like">
                <%= image_tag("like",class:"tweet_btn")%>
                <%=tweet.likers_count%>
              </div>
             <%end%>
            <%end%>
            <div class="tweet_like">
              <%=link_to image_tag("comment", class:"tweet_btn"),tweet_path(tweet)%>
            </div>
          </div>
          <%# /like%>

       <div class="tweet-wrap">
         <label class="tweet-btn" ></label>
         <div class="tweet-item"><%= tweet.text%></div>
       </div>
       
      </div>
    </div>
    <%end%>
   <%end%>
   <%else%>
   <div class="favorite_tweet_main">
       <div class="not_tweet_favorite">
         <%= link_to image_tag("tweets",class:"not_favorite_image"),search_tweets_path %>
          <p>検索したSTORYはありません...</p>
       </div>
   <%end%>
   </div>
 </div>
</div>
</div>
<%# /STORY一覧%>

app/views/shared/_user_profile.html.erb
<%= form_with model: @user, url: user_registration_path, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報入力
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>
  <div id="image-list"></div>
  <div class="form-group">
    <div class='form-text-wrap'>
    <%= f.file_field :image, class: 'olddd', id:"message-image" %>
    </div>
    </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) furima太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
    <p class='form-info-text'>
      安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
    </p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_kana, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>

  <div class="form-group">
     <div class='form-text-wrap'>
       <label class="form-text">SHOP名</label>
       <span class="indispensable">後でもOK</span>
     </div>
    <div class='input-name-wrap'>
      <%= f.text_area :shop_name, class:"input-name", id:"shop_name", placeholder:"例) 山田" %>
    </div>
  </div>

   <div class="form-group">
     <div class='form-text-wrap'>
       <label class="form-text">SHOPストーリー</label>
       <span class="indispensable">後でもOK</span>
      </div>
     <div class='input-name-wrap'>
       <%= f.text_area :shop_text, class:"shop_story", id:"shop_text", placeholder:"例) 山田" %>
     </div>
   </div>

   <div class="form-group">
    <h2 class='form-bottom-text'>
      「会員登録」のボタンを押すことにより、
      <span>利用規約</span>
       <br>に同意したものとみなします
     </h2>
    </div>
   <div class='register-btn'>
     <%= f.submit "会員登録" ,class:"register-red-btn" %>
   </div>
  </div>
<% end %>

app/views/shared/_user_side_bar.html.erb
<% if @user.id == current_user.id%>
<div class="user_menu">
     <%= link_to tweetfavorite_users_path do%>
      <div class="user_side_bar">
       <%= image_tag("like",class:"user_menu_image")%>
       <div class="user_side_text">お気に入りのSTORY</div>
      </div>
     <%end%>

    <%= link_to favorite_users_path do%>
     <div class="user_side_bar">
      <%= image_tag("star",class:"user_menu_image")%>
       <div class="user_side_text">お気に入りのITEM</div>
     </div>
    <%end%>

    <%= link_to buy_users_path do%>
     <div class="user_side_bar">
      <%= image_tag("danboul",class:"user_menu_image")%>
       <div class="user_side_text">購入履歴</div>
     </div>
    <%end%>

    <%= link_to sale_users_path do%>
     <div class="user_side_bar">
      <%= image_tag("money",class:"user_menu_image")%>
       <div class="user_side_text">売り上げ管理</div>
     </div>
    <%end%>

    <%= link_to rooms_path do%>
     <div class="user_side_bar">
      <%= image_tag("message",class:"user_menu_image")%>
       <div class="user_side_text">CHAT</div>
     </div>
    <%end%>

    <%= link_to notifications_path do%>
     <div class="user_side_bar">
      <%= image_tag("bell",class:"user_menu_image")%>
       <div class="user_side_text">お知らせ</div>
     </div>
    <%end%>

    <%= link_to root_path do%>
     <div class="user_side_bar">
      <%= image_tag("home",class:"user_menu_image")%>
       <div class="user_side_text">HOME</div>
     </div>
    <%end%>

    <%= link_to destroy_user_session_path, method: :delete do%>
     <div class="user_side_bar">
      <%= image_tag("logout",class:"user_menu_image")%>
       <div class="user_side_text">LOGOUT</div>
     </div>
    <%end%>
  <%end%>
</div>