config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :shops do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      get :favorite
      get :tweetfavorite
      get :sale
      get :buy
    end
    member do
      get :follow
      get :followees
      get :follower
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :tweets do
    resources :tweet_comments
    collection do
      get 'search'
    end
    member do
      get :favorite
    end
  end
  resources :notifications, only: [:index]
  resources :rooms, only:[:index,:create,:show]
  resources :messages, only:[:create]

  resources :items do
    member do
      get :favorite
    end
    collection do
      get 'search'
      get 'category'
    end
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_one_attached :image
  belongs_to_active_hash :category
  belongs_to_active_hash :delivery_charge
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :day
  belongs_to :user
  belongs_to :shop, optional: true

  has_one :order
  has_many :comments, dependent: :destroy
  acts_as_likeable

  has_many :notifications, dependent: :destroy


  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and tweet_id = ? and action = ? ", current_user.id, user_id, id, 'itemlike'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        item_id: id,
        visited_id: user_id,
        action: 'itemlike'
      )
      unless notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
      end
    end
  end


  def create_notification_comment!(current_user, comment_id, item_id)
    # item = Item.where(item_id: item.id)
    temp_ids = Comment.select(:user_id).where(item_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'], item_id)
    end
    save_notification_comment!(current_user, comment_id, user_id, item_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id, item_id)
    # taiki = Item.left_joins(:notifications).where(items: {item_id: item_id}).select("user_id")
    # visitor = current_user.id
    # if visitor == taiki
    notification = current_user.active_notifications.new(
      item_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
  #   else
  #   notification = current_user.active_notifications.new(
  #     item_id: id,
  #     comment_id: comment_id,
  #     visited_id: visited_id,
  #     action: 'usercomment'
  #   )
  # end

    unless notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
    end

  end

  def was_attached?
    self.image.attached?
  end

  with_options presence: true do
    validates :text
    validates :name
    validates :image

   with_options numericality: { other_than: 1, message: 'を選択して下さい' } do
    validates :category_id
    validates :delivery_charge_id
    validates :prefecture_id
    validates :day_id
   end
   with_options format: {with: /\A[0-9]+\z/} do
    validates :price, numericality: { 
      greater_than: 300, less_than: 9999999
       }
   end
 end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy, :favorite]
  before_action :order_set, only: [:edit, :update, :destroy]
  before_action :search_product

  
  def index
    @items = Item.all.order("created_at DESC")
    @tweets = Tweet.limit(10).order("created_at DESC")
    @results = @p.result.order("created_at DESC")
    set_item_column

    @results = @items.page(params[:page]).per(16)
  end

  def new
    if current_user.shop.present?
    @item = Item.new
    else
      redirect_to new_shop_path(current_user)
    end
  end

  def create
    @item = Item.new(items_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
    @user = @item.user
    @items = @user.items
    @shop = @user.shop
  end
  
  def update
    if @item.update(items_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @items = Item.all
    @results = @p.result.page(params[:page]).per(16).order("created_at DESC")
    set_item_column

  end

  def favorite
    current_user.toggle_like!(@item)
    @item.create_notification_like!(current_user)
    redirect_to request.referer
  end


  private
  def items_params
    params.require(:item).permit(:name, :text, :category_id, :delivery_charge_id, :prefecture_id, :day_id, :price, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    unless Item.find(params[:id]).user.id == current_user.id
      redirect_to action: :index
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def order_set
    if @item.user_id == current_user.id && @item.order == nil
      set_item
    else
      redirect_to root_path
    end
  end



  def search_product
    @p = Item.ransack(params[:q])
  end

  def set_item_column
    @item_name = Item.select("name").distinct
    @item_category = Category.all
    @item_delivery_charge = DeliveryCharge.all
    @item_day = Day.all
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<%#user/showなどに使われている%>

<div class='item-contents'>
    <ul class='item-lists'>

      <% if @items.present? %>
      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(id: item.id) do %>
        <div class='item-img-content'>
          <%= link_to image_tag(item.image, class: 'item-img' ), item_path(id: item.id)%>

          <% if item.order != nil %>
          <div class='sold-out'>
            <%= image_tag("sold_out")%>
          </div>
          <% end%>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= link_to item.name, item_path(item.id), class: 'item-name'%>
          </h3>
          <div class='item-price'>
            <span>¥<%= item.price %>円<br></span>
            <div class='star-btn'>
              <%# <%= image_tag "star.png", class:"star-icon" %>
              <%# <span class='star-count'>0</span> %>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>

      <% else %>
          <h3 class='item-non'>
            商品が出品されていません。
          </h3>
        </div>
      <% end %>
      
    </ul>
  </div>
  
  <%# /商品一覧 %>

app/views/items/edit.html.erb
<%= render partial: "shared/item_box"%>
<%= render partial: "shared/second-footer" %>

app/views/items/index.html.erb
<%= render partial: 'shared/header'%>

<div class='main'>

  <%# TOP画像 %>
  <div class='title-contents'>
   <div class="top_image">
   <%= image_tag "orange", class: "main_image"%>
   <p>あなたの<span>想い</span>がつながる場所。</p>
   <div class="main_image_text"><span>Give</span>で挑戦しよう。</div>
   <%# <%= image_tag("main_image2",class:"main_image2")%>
   </div>
  </div>
  <%# //TOP画像 %>
  
  <%# SELECT部分 %>
  <div class="top_choice">
   <h1 class="item_title">SELECT</h1>
   
   <%= link_to search_items_path do%>
   <div class="story-product">
    <div class="item_search_page">
     <div class="select_box">
     <%= image_tag("item_main", class:"shopping_image")%>
     <div class="product-btn">ITEM</div>
     </div>
    </div>
    <%end%>

    <%= link_to search_tweets_path do%>
    <div class="tweet_search_page">
    <div class="select_box">
     <%= image_tag("tweet_main", class:"shopping_image")%>
     <div class="product-btn">STORY</div>
    </div>
    </div>
    <%end%>
   </div>
  </div>
  <%# //SELECT部分 %>
  <div class="item_tweet_main">
  <div class="title_new_content">
  <h1 class="item_title">STORY</h1>
  <%# <%= image_tag("new",class:"tweet_new_title")%>
  </div>
       <div class="ososo">
   <div class="tweet_scroll_search">
   <%= link_to "さらに見る",search_tweets_path %>
   </div>
  <%= render partial: "shared/tweet_scroll"%>
  </div>

  <%# Itemsearch %>
  <div class="title_new_content">
 <h1 class="item_title">ITEM</h1>
 <%# <%= image_tag("new",class:"item_new_title")%>
 </div>
 <%= render partial: "shared/item_search"%>
</div>

 <%# <%= render partial: "shared/second-footer" %>

app/views/items/new.html.erb
<%= render partial: "shared/item_box"%>
<%= render partial: "shared/second-footer" %>

app/views/items/search.html.erb
<%= render partial: 'shared/header'%>

 <div class="main">
   <h1 class="item_title">
    ITEM
   </h1>
  <%= render partial: "shared/item_search"%>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>


<div class="main">
<%# 商品画像 %>
<div class="item-show">
  <div class="item-box">
  <div class="left-image">
    <div class="item-image-content">
      <%= image_tag @item.image ,class:"item-box-image" %>
      <% if @item.order != nil%>
      <div class="sold-out">
        <%= image_tag("sold_out")%>
      </div>
      <% end %>
     </div>
    </div>

    <%# 商品説明 %>
    <div class="right-item">
     <h2 class="name"><%= @item.name %></h2>
      <div class="item-price-box">
       <span class="item-price">¥<%= @item.price %></span>
       <span class="item-postage"><%= @item.delivery_charge.name %></span>
      </div>

    <% if user_signed_in? && @item.order == nil %>
     <% if current_user.id == @item.user_id %>
        <%= link_to image_tag("edit", class: "item-edit-btn"), edit_item_path(@item.id), method: :get %>
        <%= link_to image_tag("destroy",class:"item-destroy"), item_path(@item.id), method: :delete, data: {confirm: "削除しますか？"} %>
       <% else %>
       <%= link_to "購入画面に進む", item_orders_path(@item.id), method: :get,class:"item-buy-btn"%>
       <% end %>
      <% end %>

      <%# like/like数 %>
      <div class="likesss">
      <div classs="item_like_ask">
      <% if user_signed_in? %>
        <%= link_to favorite_item_path do %>
        <% if current_user.likes?(@item)%>
          <%= image_tag("redheart",class:"heart")%>
          <%= @item.likers_count%>
         
        <%else%>
          <%= image_tag("blackheart",class:"heart")%>
          <%= @item.likers_count%>
        <%end%>
        <%end%>
        </div>
       </div>
       <%end%>

       <%# 商品の情報 %>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">ショップ</th>
          <td class="detail-value"><%=link_to @shop.name, user_path(@item.user.id) %></td>
        </tr>
        <tr>
          <th class="detail-item">代表</th>
          <td class="detail-value"><%=link_to @item.user.nickname, user_path(@item.user_id) %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.delivery_charge.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.day.name %></td>
        </tr>
      </tbody>
    </table>
    
     <div class="item-explain-box">
      <%= @item.text %>
    </div>


      <%# コメント %>
    <div class="comment_title">コメント</div>
     <% @comments.each do |comment| %>
     <div class="comments">
      <div class="comment-content">
       <div class="tweet_comment_nickname_image">
        <%= image_tag comment.user.image, class:'item_comment_user_image',id: 'message-image'%>
         <div class="comment-name">
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %></strong>
         </div>
       </div>
       <div class="comment_text_time">
       <div class="comment_text">
        <%= comment.text %>
         </div>
         <div class="show_tweet_time">
        <%= " #{time_ago_in_words(comment.created_at)}前" %>
       </div>
       </div>
     
     </div>
    </div>
    <% end %>

   <div class="comment-box"> 
    <% if @item.order == nil %>
     <% if user_signed_in? %>
     <%= form_with(model: [@item, @comment], local:true) do |t|%>
       <%= t.text_area :text, class: "comment-form", placeholder: "コメント", maxlength:"140" %>
        <p class="comment-warn">
        相手のことを考えたコメントを心がけましょう。</p>
        <%= t.submit "コメントする", class: :comment_btn %>
       </div>
      <% end %>
     <% else %>
       <strong><p>コメントの投稿には新規登録/ログインが必要です</p>
       </strong>
    <% end %>
    <%end%>
   </div>
   </div>
    </div>
     </div>
     </div>
        <div class="show_item_shop"><%= @user.shop.name%>
         </div>
        <%= render partial: 'items/item' %>
</div>

<%= render "shared/second-footer" %>